### ISSUE TITLE
Saving Question to Board

### ISSUE THREAD

**Issue by jennykim1016** [dragonrollers/thoughtbubble-app#28]
Hi @potsui ,

I was just testing the board and saving reflections, and realized that even though we can save a new board, we are not able to save new thoughts to a new board. Could you please check this? Thanks!

**Comment by potsui** [comment]
@jennykim1016 that's not pushed up yet --- was working on it last night in a local branch

**Comment by bnortz** [comment]
Saw a question on a board in the database and figured I'd comment in here - from a firebase blog post I read I learned of a good practice that could be useful here, that I've been starting to use other places. Potentially a good way to store the questions is with the path "boards/"+boardID+"/"+questionID, and have the value at that path be set to "true". That way it's easy to see if a question belongs to a board (if we need to do that, can't remember) with something like dataSnapshot.exists, since we know the exact path, and you can get the questionIDs from a board with .getKey() methods (or something similar to that)

**Comment by potsui** [comment]
Implemented with #62
